ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.dacha.ApplicationKt.module

storage:
  clickhouse:
    url: "http://default:@localhost:8123/log-collector"
  redis:
    url: "redis://localhost:6379"
    topic: "logs"